on:
  workflow_dispatch:
  push:

jobs:
  test_linux:
    name: ${{ matrix.os }} (${{ matrix.browser }})
    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, firefox, webkit]
        os: [ubuntu-18.04]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 12
    - name: Install dependencies
      run: npm ci      
    - name: Install Playwright      
      run: npx playwright install ${{ matrix.browser }}
    - name: Run Playwright tests      
      run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- npm run test:e2e -- --browser=${{ matrix.browser }}
      env:
        CI: true
        DEBUG: pw:install
      if: always()
    - uses: actions/upload-artifact@v1
      if: always()
      with:
        name: ${{ matrix.browser }}-${{ matrix.os }}-test-results
        path: test-results
  
  
